FaxrHospital/Controllers/DoctorController.cs
using FaxrHospital.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FaxrHospital.Controllers
{
    public class DoctorController : Controller
    {
        public readonly ApplicationDbContext _db;
        public DoctorController(ApplicationDbContext db) => _db = db;

        public IActionResult Index(string sortOrder, string searchString)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["SpecSortParm"] = sortOrder == "Spec" ? "spec_desc" : "Spec";
            ViewData["OtdelSortParm"] = sortOrder == "Otdel" ? "otdel_desc" : "Otdel";
            ViewData["QualSortParm"] = sortOrder == "Qual" ? "qual_desc" : "Qual";

            var doctor = from a in _db.Doctor select a;

            if (!String.IsNullOrEmpty(searchString))
            {
                doctor = doctor.Where(a => a.Name.Contains(searchString) ||
                                           a.Speciality.Contains(searchString) || 
                                           a.Qualification.Contains(searchString) || 
                                           a.OtdelenieId.ToString().Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    doctor = doctor.OrderByDescending(a => a.Name);
                    break;
                case "Spec":
                    doctor = doctor.OrderBy(s => s.Speciality);
                    break;
                case "spec_desc":
                    doctor = doctor.OrderByDescending(s => s.Speciality);
                    break;
                case "Otdel":
                    doctor = doctor.OrderBy(s => s.Otdelenie.Name);
                    break;
                case "otdel_desc":
                    doctor = doctor.OrderByDescending(s => s.Otdelenie.Name);
                    break;
                case "Qual":
                    doctor = doctor.OrderBy(s => s.Qualification);
                    break;
                case "qual_desc":
                    doctor = doctor.OrderByDescending(s => s.Qualification);
                    break;
                default:
                    doctor = doctor.OrderBy(a => a.Name);
                    break;
            }
            return View(doctor);
        }

        public IActionResult Add()
        {
            IEnumerable<SelectListItem> OtdelenieList = _db.Otdelenie.ToList().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            ViewBag.OtdelenieList = OtdelenieList;

            return View();
        }

        [HttpPost]
        public IActionResult Add(Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                _db.Doctor.Add(doctor);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Doctor? doctorFromDb = _db.Doctor.Find(id);
            if (doctorFromDb == null)
            {
                return NotFound();
            }

            IEnumerable<SelectListItem> OtdelenieList = _db.Otdelenie.ToList().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            ViewBag.OtdelenieList = OtdelenieList;

            return View(doctorFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                _db.Doctor.Update(doctor);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            Doctor? doctorFromDb = _db.Doctor.Find(id);
            if (doctorFromDb == null)
            {
                return NotFound();
            }
            _db.Doctor.Remove(doctorFromDb);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FaxrHospital/Controllers/DrugController.cs
using FaxrHospital.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FaxrHospital.Controllers
{
    public class DrugController : Controller
    {
        public readonly ApplicationDbContext _db;
        public DrugController(ApplicationDbContext db) => _db = db;

        public IActionResult Index(string sortOrder, string searchString)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["IllnesSortParm"] = sortOrder == "Illnes" ? "illnes_desc" : "Illnes";

            var drug = from a in _db.Drug select a;

            if (!String.IsNullOrEmpty(searchString))
            {
                drug = drug.Where(a => a.Name.Contains(searchString) || a.IllnesId.ToString().Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    drug = drug.OrderByDescending(a => a.Name);
                    break;
                case "Illnes":
                    drug = drug.OrderBy(s => s.IllnesId);
                    break;
                case "illnes_desc":
                    drug = drug.OrderByDescending(s => s.IllnesId);
                    break;
                default:
                    drug = drug.OrderBy(a => a.Name);
                    break;
            }
            return View(drug);
        }

        public IActionResult Add()
        {
            IEnumerable<SelectListItem> IllnesList = _db.Illnes.ToList().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            ViewBag.IllnesList = IllnesList;

            return View();
        }

        [HttpPost]
        public IActionResult Add(Drug drug)
        {
            if (ModelState.IsValid)
            {
                _db.Drug.Add(drug);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Drug? drugFromDb = _db.Drug.Find(id);
            if (drugFromDb == null)
            {
                return NotFound();
            }

            IEnumerable<SelectListItem> IllnesList = _db.Illnes.ToList().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            ViewBag.IllnesList = IllnesList;

            return View(drugFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Drug drug)
        {
            if (ModelState.IsValid)
            {
                _db.Drug.Update(drug);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            Drug? drugFromDb = _db.Drug.Find(id);
            if (drugFromDb == null)
            {
                return NotFound();
            }
            _db.Drug.Remove(drugFromDb);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FaxrHospital/Controllers/OtdelenieController.cs
using FaxrHospital.Models;
using Microsoft.AspNetCore.Mvc;

namespace FaxrHospital.Controllers
{
    public class OtdelenieController : Controller
    {
        public readonly ApplicationDbContext _db;
        public OtdelenieController(ApplicationDbContext db) => _db = db;

        public IActionResult Index(string sortOrder, string searchString)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            var otdelenie = from a in _db.Otdelenie select a;

            if (!String.IsNullOrEmpty(searchString))
            {
                otdelenie = otdelenie.Where(a => a.Name.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    otdelenie = otdelenie.OrderByDescending(a => a.Name);
                    break;
                default:
                    otdelenie = otdelenie.OrderBy(a => a.Name);
                    break;
            }
            return View(otdelenie);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Otdelenie otdelenie)
        {
            if (ModelState.IsValid)
            {
                _db.Otdelenie.Add(otdelenie);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Otdelenie? otdelenieFromDb = _db.Otdelenie.Find(id);
            if (otdelenieFromDb == null)
            {
                return NotFound();
            }
            return View(otdelenieFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Otdelenie otdelenie)
        {
            if (ModelState.IsValid)
            {
                _db.Otdelenie.Update(otdelenie);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            Otdelenie? otdelenieFromDb = _db.Otdelenie.Find(id);
            if (otdelenieFromDb == null)
            {
                return NotFound();
            }
            _db.Otdelenie.Remove(otdelenieFromDb);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FaxrHospital/Controllers/PacientController.cs
using FaxrHospital.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FaxrHospital.Controllers
{
    public class PacientController : Controller
    {
        public readonly ApplicationDbContext _db;
        public PacientController(ApplicationDbContext db) => _db = db;

        public IActionResult Index(string sortOrder, string searchString)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["SexSortParm"] = sortOrder == "Sex" ? "sex_desc" : "Sex";
            ViewData["PassportSortParm"] = sortOrder == "Passport" ? "passport_desc" : "Passport";
            ViewData["PhoneSortParm"] = sortOrder == "Phone" ? "phone_desc" : "Phone";
            ViewData["BirthSortParm"] = sortOrder == "Birth" ? "birth_desc" : "Birth";
            ViewData["AdressSortParm"] = sortOrder == "Adress" ? "adress_desc" : "Adress";


            var pacient = from a in _db.Pacient select a;

            if (!String.IsNullOrEmpty(searchString))
            {
                pacient = pacient.Where(a => a.Name.Contains(searchString) ||
                                             a.Sex.Contains(searchString) ||
                                             a.Passport.Contains(searchString) ||
                                             a.Phone.Contains(searchString) ||
                                             a.Birthday.ToString().Contains(searchString) ||
                                             a.Adress.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    pacient = pacient.OrderByDescending(a => a.Name);
                    break;
                case "Sex":
                    pacient = pacient.OrderBy(s => s.Sex);
                    break;
                case "sex_desc":
                    pacient = pacient.OrderByDescending(s => s.Sex);
                    break;
                case "Passport":
                    pacient = pacient.OrderBy(s => s.Passport);
                    break;
                case "passport_desc":
                    pacient = pacient.OrderByDescending(s => s.Passport);
                    break;
                case "Phone":
                    pacient = pacient.OrderBy(s => s.Phone);
                    break;
                case "phone_desc":
                    pacient = pacient.OrderByDescending(s => s.Phone);
                    break;
                case "Birth":
                    pacient = pacient.OrderBy(s => s.Birthday);
                    break;
                case "birth_desc":
                    pacient = pacient.OrderByDescending(s => s.Birthday);
                    break;
                case "Adress":
                    pacient = pacient.OrderBy(s => s.Adress);
                    break;
                case "adress_desc":
                    pacient = pacient.OrderByDescending(s => s.Adress);
                    break;
                default:
                    pacient = pacient.OrderBy(a => a.Name);
                    break;
            }
            return View(pacient);
        }

        public IActionResult Add()
        {
            IEnumerable<SelectListItem> OtdelenieList = _db.Otdelenie.ToList().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            ViewBag.OtdelenieList = OtdelenieList;

            return View();
        }

        [HttpPost]
        public IActionResult Add(Pacient pacient)
        {
            if (ModelState.IsValid)
            {
                _db.Pacient.Add(pacient);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Pacient? pacientFromDb = _db.Pacient.Find(id);
            if (pacientFromDb == null)
            {
                return NotFound();
            }

            IEnumerable<SelectListItem> OtdelenieList = _db.Otdelenie.ToList().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            ViewBag.OtdelenieList = OtdelenieList;

            return View(pacientFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Pacient pacient)
        {
            if (ModelState.IsValid)
            {
                _db.Pacient.Update(pacient);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            Pacient? pacientFromDb = _db.Pacient.Find(id);
            if (pacientFromDb == null)
            {
                return NotFound();
            }
            _db.Pacient.Remove(pacientFromDb);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FaxrHospital/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FaxrHospital</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FaxrHospital.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-info">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Faxr Hospital</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Отделения</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Otdelenie" asp-action="Index">Все отделения</a>
                                <a class="dropdown-item" asp-controller="Otdelenie" asp-action="Add">Добавить новое</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Доктора</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Doctor" asp-action="Index">Все доктора</a>
                                <a class="dropdown-item" asp-controller="Doctor" asp-action="Add">Добавить нового</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Пациенты</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Pacient" asp-action="Index">Все пациенты</a>
                                <a class="dropdown-item" asp-controller="Pacient" asp-action="Add">Добавить нового</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Болезни</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Illnes" asp-action="Index">Все болезни</a>
                                <a class="dropdown-item" asp-controller="Illnes" asp-action="Add">Добавить новую</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Препараты</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Drug" asp-action="Index">Все препараты</a>
                                <a class="dropdown-item" asp-controller="Drug" asp-action="Add">Добавить новый</a>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="text-secondary">Фахриева Айгуль Айдаровна</div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-info">
        <div class="container">
            <div class="row">
                <div class="col">
                    &copy; @DateTime.Now.Year - Faxr Hospital
                </div>
                <div class="col">
                    Сайт сделала Фахриева Айгуль Айдаровна!
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>