FaxrHospital/Models/Illnes.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace FaxrHospital.Models
{
    public class Illnes
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Обязательное поле!")]
        [Display(Name = "Название")]
        public string Name { get; set; }

        [Display(Name = "Описание")]
        public string? Description { get; set; }
    }
}

FaxrHospital/Controllers/IllnesController.cs
using FaxrHospital.Models;
using Microsoft.AspNetCore.Mvc;

namespace FaxrHospital.Controllers
{
    public class IllnesController : Controller
    {
        public readonly ApplicationDbContext _db;
        public IllnesController(ApplicationDbContext db) => _db = db;

        public IActionResult Index(string sortOrder, string searchString)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            var illnes = from a in _db.Illnes select a;

            if (!String.IsNullOrEmpty(searchString))
            {
                illnes = illnes.Where(a => a.Name.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    illnes = illnes.OrderByDescending(a => a.Name);
                    break;
                default:
                    illnes = illnes.OrderBy(a => a.Name);
                    break;
            }
            return View(illnes);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Illnes illnes)
        {
            if (ModelState.IsValid)
            {
                _db.Illnes.Add(illnes);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Illnes? illnesFromDb = _db.Illnes.Find(id);
            if (illnesFromDb == null)
            {
                return NotFound();
            }
            return View(illnesFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Illnes illnes)
        {
            if (ModelState.IsValid)
            {
                _db.Illnes.Update(illnes);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            Illnes? illnesFromDb = _db.Illnes.Find(id);
            if (illnesFromDb == null)
            {
                return NotFound();
            }
            _db.Illnes.Remove(illnesFromDb);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FaxrHospital/Views/Illnes/Add.cshtml
@model Illnes

@{
    ViewData["Title"] = "Добавление";
}

<div class="d-flex justify-content-md-start">
    <div class="card text-white bg-info mb-3">
        <div class="card-header">Новая болезнь</div>
        <div class="card-body">
            <form method="post">
                <div class="mb-3">
                    <label class="p-1" for="floatingInput" asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="p-1" for="floatingInput" asp-for="Description"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="btn-group" role="group">
                    <a asp-controller="Illnes" asp-action="Index" class="btn btn-dark w-100">Вернуться</a>
                    <button type="submit" class="btn btn-success w-100">Создать</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

FaxrHospital/Views/Illnes/Edit.cshtml
@model Illnes

@{
    ViewData["Title"] = "Изменение";
}

<div class="d-flex justify-content-md-start">
    <div class="card text-white bg-info mb-3">
        <div class="card-header">Изменение болезни</div>
        <div class="card-body">
            <form method="post">
                <div class="mb-3">
                    <label class="p-1" for="floatingInput" asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="p-1" for="floatingInput" asp-for="Description"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="btn-group" role="group">
                    <a asp-controller="Illnes" asp-action="Index" class="btn btn-dark w-100">Вернуться</a>
                    <button type="submit" class="btn btn-warning w-100">Изменить</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

FaxrHospital/Views/Illnes/Index.cshtml
@model IEnumerable<Illnes>

@{
    ViewData["Title"] = "Фахриева Айгуль Айдаровна";
}

<div class="row justify-content-end w-100 mt-4">
    <div class="col-6">
        <form asp-action="Index" method="get">
            <div class="form-actions no-color">
                <p>
                    <strong class="w-100 pb-1" style="font-size: 1.1rem">Поиск:</strong>
                    <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" class="w-50 border-info" />
                    <button type="submit" class="btn btn-info w-25">Искать</button>
                </p>
            </div>
        </form>
    </div>
</div>
<table class="table table-sm table-hover w-100 mt-3 pb-2 cell-centered">
    <thead>
        <tr>
            <th>
                <h2 class="text-center text-primary">
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" class="link link-primary page-link">Болезни</a>
                </h2>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var illnes in Model)
        {
            <tr>
                <td>
                    <div class="row">
                        <div class="col-2">
                            <a asp-controller="Illnes" asp-action="Edit" asp-route-id="@illnes.Id" class="btn btn-outline-warning w-100">Редактировать</a>
                        </div>
                        <div class="col-3">
                            @illnes.Name
                        </div>
                        <div class="col-5">
                            @illnes.Description
                        </div>
                        <div class="col-2">
                            <a asp-controller="Illnes" asp-action="Delete" asp-route-id="@illnes.Id" class="btn btn-outline-danger w-100">Удалить</a>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>